### ISSUE TITLE
Retina Download?

### ISSUE THREAD

**Issue by mbomb007** [m-ender/vscode-retinate#9]
I see some code in the repo that seems to involve downloading Retina. Is there a way to easily or automatically download Retina after installing this VS Code extension? Ever since learning Retina, I still use it for productivity, but I happened to notice you had this extension, so I figured I might not need to use TIO anymore.

**Comment by m-ender** [comment]
It's been a while, but I'm pretty sure @lukasniemeier just added that for the CI, and I've definitely never used it. It's probably easiest to just get it from the Retina repo and set up the path in the extension settings. If someone's actually using this extension, I might look into improving the setup process at some point though.

**Comment by mbomb007** [comment]
Okay. Then how do I get Retina to work? I downloaded the latest release for Win 64, but the install is not a self-contained application. I have the Windows .NET 3.5 feature enabled (which includes .NET 2.0 and 3.0).

> A fatal error occurred, the required library hostfxr.dll could not be found.
> If this is a self-contained application, that library should exist in [C:\Program Files\dotnet\].
> If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.

**Comment by mbomb007** [comment]
Figured it out. I had to download the .NET Core 2.2 runtime.

Maybe add this link to your README: https://dotnet.microsoft.com/download/dotnet-core/2.2
